### ISSUE TITLE
Cassandra-driver version

### ISSUE THREAD

**Issue by devnut** [cequel/cequel#235]
I am a bit confused by the versions of Cequel vs cassandra-driver.  

In the docs for Cequel it reads that CQL3 is supported via cassandra-driver.  But the version in the gemspec is '~>1.0'.

If I'm reading the cassandra-driver docs correctly (https://github.com/datastax/ruby-driver/blob/master/CHANGELOG.md), it says that CQL3 was added in 2.0.0.

Is there a branch somewhere of Cequel that is using the 2.x branch of the official Datastax ruby driver?

- Greg

**Comment by outoftime** [comment]
@devnut you're confusing the protocol version (low-level) with the CQL version (high-level). `cassandra-driver` has never supported anything earlier than CQL3 (there was no native protocol prior to CQL3).

Let's leave this open though since apparently Cequel is out of date with its `cassandra-driver` dependency

**Comment by devnut** [comment]
Ahh, that makes sense!   

... must.. get... more... ...coffee....
