### ISSUE TITLE
Cequel still alive

### ISSUE THREAD

**Issue by marktermaat** [cequel/cequel#248]
Just wondering, since there hasn't been any activity the last couple of months, and the official cassandra-driver is several versions further already. Is Cequel still being maintained? Is this just a small dip, or is it bleeding to death?

**Comment by lesliev** [comment]
Looks unmaintained. That said, there are forks which bump Cassandra driver:
https://github.com/Galeria-Kaufhof/cequel/commit/51afb3cf9b302ce805fa6fca6be458b56cb98c91

That does seem to work, up until Cassandra 2.1.8, but Cequel breaks with Cassandra 2.2.0 because it tries to use system columns which no longer exist to get schema info. 

Ubuntu (14.04) upgraded the Cassandra package from 2.1.8 to 2.2.0 on August 2 which broke my local installation so I had to hold the package at 2.1.8.

In any case if you use Cequel beyond its sell-by date you're advised to test well and I for one would appreciate news of any gotchas.

**Comment by makrisoft** [comment]
@lesliev I made the same mistake of upgrading to 2.2.0 and saw that migrations failed.

@outoftime are you actively working on a 2.2.0 fix? Or should we start working on it ourselves?

**Comment by lesliev** [comment]
If you do fork Cequel, be aware of this bug we fixed a few days ago:
https://github.com/visfleet/cequel/commit/006dac39cfcd929745d55eab889ed57b73441bc9

Cequel was leaking threads when an error caused it to reconnect.
I've not made a PR because I've not yet gotten the tests properly working.

**Comment by devnut** [comment]
This does not seem to work with Rails 3.2.22 - was that intentional?

Is there a version somewhere that works with cassandra-driver 2.1.3 (or 2.1.4) and Rails 3.2.22?

- Greg
