### ISSUE TITLE
generate id automatically with type integer

### ISSUE THREAD

**Issue by yeudit** [cequel/cequel#258]
is there a way to generate id automatically and the id column type is int?

**Comment by outoftime** [comment]
@yeudit there isn’t. I suppose one could generate a UUID and then save its integer representation in an int column, but I see no reason not to just store it as a UUID in that case.

It’s not possible to have auto-incrementing integer columns in a distributed database like Cassandra, because that would require close coordination between all nodes, which would defeat the purpose of a masterless data store.
