### ISSUE TITLE
Use belongs_to with ActiveRecord models

### ISSUE THREAD

**Issue by yoonwaiyan** [cequel/cequel#312]
Hi, I'm setting up one model for my project using Cassandra while other models are using ActiveRecord with PostgreSQL database. This is my new model using Cequel:

```ruby
class StockMovement
  include Cequel::Record

  # belongs_to :user
  # belongs_to :user_profile
  key :id, :uuid, auto: true
  key :user_id, :bigint
  key :user_profile_id, :bigint, order: :asc
  column :stock_before_update, :bigint
  column :stock_after_update, :bigint

  timestamps
end
```

The problem rises when I wanted to use belongs_to association as I want to query stock movements based on user id and/or profile id, but when I use belongs_to it doesn't work(unable to run migration properly) as both User and Profile are using ActiveRecord so including Cequel::Record broke other ActiveRecord configuration. 

Then I try to workaround by setting user id and profile id and non-key column of id, which works in migration but when inserting data I only get one record for each combination of user and profile but it should have multiple stock movements within the same profile.

So, I've tried to set id as one of the key besides user and profile, it works but when I want to query stock movements that belongs to this profile:
```ruby
StockMovement.where(user_id:1, user_profile_id: 1)
```
now it raised up this error:
```ruby
Cequel::Record::IllegalQuery: Can't scope key column user_id without also scoping id
from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/cequel-d966eed4a9dc/lib/cequel/record/record_set.rb:931:in `block in method_missing'
```

adding allow_filtering returns the same message. How do I configure the model such that each profile can have multiple stock movments without changing user and profile to use Cassandra(that would be a huge migration to change the entire database) and Cequel will execute the query without error? Really appreciate any help as I'm just starting to learn Cassandra.

**Comment by pezra** [comment]
I am on vacation for the next week or so. I will merge/give feed back once I am back in front of a computer.

**Comment by pezra** [comment]
@yoonwaiyan, the behavior you are seeing is intentional. `belongs_to` in cequel only works with other cequel models. It is impractical to support active record models in associations.

The scoping behavior you encountered is inherent to Cassandra. Keys must be used in the order they are defined so to support the query your table would need to be defined as

```
  key :user_id, :bigint
  key :user_profile_id, :bigint, order: :asc
  key :id, :uuid, auto: true
```

Cequel will reorder the keys from the query to match the table but if you want to filter on a particular key you must filter all the preceding ones too.

I suggest reading some Cassandra data modeling tutorials like the ones at <http://www.datastax.com/resources/data-modeling> and <http://www.datastax.com/dev/blog/basic-rules-of-cassandra-data-modeling>. These will help you better understand some of the basic limitations and advantages of Cassandra.
