### ISSUE TITLE
ActiveRecord like enum

### ISSUE THREAD

**Issue by phoet** [cequel/cequel#351]
would you consider merging a PR with support for enum-support like in [ActiveRecord](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb)?

i would like to do something like this

```ruby
# instead of this with a custom mapping
column :type, :int # 1 -> type_x 2 -> type_y ...

# i would like to 
enum :type, { 1 => :type_x, 2 => :type_y ... }
```

**Comment by pezra** [comment]
That would be a great feature! I'd definitely merge a PR implementing it.

I'd prefer maintaining the current `column` class method for column definition rather than adding a new class method just for enums. Also, the value map should be keyed on the meaningful name rather than the id. Those would result in syntax like
 
```ruby
column :type, :enum, values: {type_x: 1, type_y: 2}
```

Having a form that allows an array of values would be nice too, but a lot less important. For example:

```ruby
column :type, :enum, values: [:type_x, :type_y]
```
