### ISSUE TITLE
Has Many associations in rails with cassandra CEQUEL ORM

### ISSUE THREAD

**Issue by vsachinrao** [cequel/cequel#374]
I am using cassandra as DB with Ruby on Rails. I have used CEQUEL gem to connect to cassandra. In the Parent child 1 to M relationship setup, I am facing issue that the edit, show, update, destroy actions in controller come with URL where the compound partition key of child table is represented as parentkey-childkey.

This is the reason the ChildModel.Find(Params[:id]) does not find record.

Ex. I have parent model as KPI with key KPIName Child model, KPIFields with key as KPI_KPIName and FieldName

when show action of KPI fields is called the the URL created is Localhost:3000/kpifields/kpi_kpiname-fieldname

And since KPIFields model has 2 key fields , the KPIField.Find(Params[:id]) fails with cequel arg error Missing key component(s) fieldname.

Please suggest, how I can get values of the key fields propely for parent child relationship.

Please note, I am not using Friendly Id or slug.

**Comment by pezra** [comment]
You must provide _all_ partition key fields to `#[]`. This is a limitation of cassandra.

Partitions containing just one record generally lead to terrible performance in c*. I'd suggest making the field name (at the very least) a cluster key rather than a partition key. That would allow you to use the `#[]` method the way you are trying. 

You should consider increasing your partition sizes even more. Generaly, it is better to define partitions so that they contain all the data you would want at a time. For example, if you are building a dashboard you would want all the KPIs on a particular dashboard screen in a single partition (and the same for KPI fields and values).
